### ISSUE TITLE
Fix date parse by including timezone

### ISSUE THREAD

**Issue by kirtanp98** [kirtanp98/mangaupdates-graphql-api#6]
Currently parsed dates does not include the timezone when it parses, so the time is off by a couple of hours.
`dates-fns` doesn't have a way to parse timezone abbreviations, so we need to figure out how we can do this.

https://github.com/kirtanp98/mangaupdates-graphql-api/blob/48b46fc5f1ca1eba294d49028affd3fbec1354cc/src/parser/MangaParser.ts#L444-L450

Mangaupdates looks like it sets all updated times in PST
![image](https://user-images.githubusercontent.com/28634279/124844346-08a8c780-df62-11eb-9c85-666385b92c5c.png)

**Comment by zain08816** [comment]
`August 2nd 2021, 10:22AM -08:00`

gets converted properly

`2021-08-02T18:22:00.000Z` 


The code is working as intended. This issue can be closed.
